const yaml = require('js-yaml');

// Clash Meta configuration object
const config = {
  port: 7890,
  socks-port: 7891,
  allow-lan: true,
  mode: 'rule',
  log-level: 'info',
  external-controller: '127.0.0.1:9090',
  ipv6: true,
  dns: {
    enable: true,
    ipv6: true,
    'enhanced-mode': 'fake-ip',
    'fake-ip-range': '28.0.0.1/8',
    'fake-ip-filter': ['+.lan', '+.local'],
    'default-nameserver': ['223.5.5.5'],
    nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query'],
  },
  proxies: [
    // Placeholder proxies; replace with actual proxy definitions
    { name: 'Proxy1', type: 'ss', server: 'server1.example.com', port: 443, cipher: 'aes-256-gcm', password: 'password' },
    { name: 'Proxy2', type: 'ss', server: 'server2.example.com', port: 443, cipher: 'aes-256-gcm', password: 'password' },
  ],
  'proxy-groups': [
    {
      name: '🚀 节点选择',
      type: 'select',
      proxies: [
        '♻️ 自动选择', '🇭🇰 香港节点', '🇨🇳 台湾节点', '🇸🇬 狮城节点', '🇯🇵 日本节点',
        '🇺🇲 美国节点', '🇬🇧 英国节点', '🇰🇷 韩国节点', '🚀 手动切换1', '🚀 手动切换2',
        '🚀 手动切换3', 'DIRECT',
      ],
    },
    { name: '🚀 手动切换1', type: 'select', proxies: ['Proxy1', 'Proxy2'] },
    { name: '🚀 手动切换2', type: 'select', proxies: ['Proxy1', 'Proxy2'] },
    { name: '🚀 手动切换3', type: 'select', proxies: ['Proxy1', 'Proxy2'] },
    {
      name: '♻️ 自动选择',
      type: 'url-test',
      proxies: ['Proxy1', 'Proxy2'],
      url: 'http://www.gstatic.com/generate_204',
      interval: 300,
      tolerance: 50,
    },
    {
      name: '💬 即时通讯',
      type: 'select',
      proxies: [
        '🚀 节点选择', '♻️ 自动选择', '🇸🇬 狮城节点', '🇭🇰 香港节点', '🇨🇳 台湾节点',
        '🇯🇵 日本节点', '🇺🇲 美国节点', '🇬🇧 英国节点', '🇰🇷 韩国节点', '🚀 手动切换1',
        '🚀 手动切换2', '🚀 手动切换3', 'DIRECT',
      ],
    },
    {
      name: '🤖 ChatGPT',
      type: 'select',
      proxies: [
        '🚀 节点选择', '♻️ 自动选择', '🇸🇬 狮城节点', '🇭🇰 香港节点', '🇨🇳 台湾节点',
        '🇯🇵 日本节点', '🇺🇲 美国节点', '🇬🇧 英国节点', '🇰🇷 韩国节点', '🚀 手动切换1',
        '🚀 手动切换2', '🚀 手动切换3', 'DIRECT',
      ],
    },
    {
      name: '🤖 AI服务',
      type: 'select',
      proxies: [
        '🚀 节点选择', '♻️ 自动选择', '🇸🇬 狮城节点', '🇭🇰 香港节点', '🇨🇳 台湾节点',
        '🇯🇵 日本节点', '🇺🇲 美国节点', '🇬🇧 英国节点', '🇰🇷 韩国节点', '🚀 手动切换1',
        '🚀 手动切换2', '🚀 手动切换3', 'DIRECT',
      ],
    },
    {
      name: '💰 Crypto',
      type: 'select',
      proxies: [
        '🚀 节点选择', '♻️ 自动选择', '🇸🇬 狮城节点', '🇭🇰 香港节点', '🇨🇳 台湾节点',
        '🇯🇵 日本节点', '🇺🇲 美国节点', '🇬🇧 英国节点', '🇰🇷 韩国节点', '🚀 手动切换1',
        '🚀 手动切换2', '🚀 手动切换3', 'DIRECT',
      ],
    },
    {
      name: '💰 PayPal',
      type: 'select',
      proxies: [
        '🚀 节点选择', '♻️ 自动选择', '🇸🇬 狮城节点', '🇭🇰 香港节点', '🇨🇳 台湾节点',
        '🇯🇵 日本节点', '🇺🇲 美国节点', '🇬🇧 英国节点', '🇰🇷 韩国节点', '🚀 手动切换1',
        '🚀 手动切换2', '🚀 手动切换3', 'DIRECT',
      ],
    },
    {
      name: '📹 油管视频',
      type: 'select',
      proxies: [
        '🚀 节点选择', '♻️ 自动选择', '🇸🇬 狮城节点', '🇭🇰 香港节点', '🇨🇳 台湾节点',
        '🇯🇵 日本节点', '🇺🇲 美国节点', '🇬🇧 英国节点', '🇰🇷 韩国节点', '🚀 手动切换1',
        '🚀 手动切换2', '🚀 手动切换3', 'DIRECT',
      ],
    },
    {
      name: '🎥 奈飞视频',
      type: 'select',
      proxies: [
        '🚀 节点选择', '♻️ 自动选择', '🇸🇬 狮城节点', '🇭🇰 香港节点', '🇨🇳 台湾节点',
        '🇯🇵 日本节点', '🇺🇲 美国节点', '🇬🇧 英国节点', '🇰🇷 韩国节点', '🚀 手动切换1',
        '🚀 手动切换2', '🚀 手动切换3', 'DIRECT',
      ],
    },
    {
      name: '📺 巴哈姆特',
      type: 'select',
      proxies: ['🇨🇳 台湾节点', '🚀 节点选择', '🚀 手动切换1', '🚀 手动切换2', '🚀 手动切换3', 'DIRECT'],
    },
    {
      name: '📺 哔哩哔哩',
      type: 'select',
      proxies: ['🎯 全球直连', '🇨🇳 台湾节点', '🇭🇰 香港节点'],
    },
    {
      name: '🌍 国外媒体',
      type: 'select',
      proxies: [
        '🚀 节点选择', '♻️ 自动选择', '🇭🇰 香港节点', '🇨🇳 台湾节点', '🇸🇬 狮城节点',
        '🇯🇵 日本节点', '🇺🇲 美国节点', '🇬🇧 英国节点', '🇰🇷 韩国节点', '🚀 手动切换1',
        '🚀 手动切换2', '🚀 手动切换3', 'DIRECT',
      ],
    },
    {
      name: '🌏 国内媒体',
      type: 'select',
      proxies: [
        'DIRECT', '🇭🇰 香港节点', '🇨🇳 台湾节点', '🇸🇬 狮城节点', '🇯🇵 日本节点',
        '🚀 手动切换1', '🚀 手动切换2', '🚀 手动切换3',
      ],
    },
    {
      name: '🇬 谷歌服务',
      type: 'select',
      proxies: [
        'DIRECT', '🚀 节点选择', '🇺🇲 美国节点', '🇭🇰 香港节点', '🇨🇳 台湾节点',
        '🇸🇬 狮城节点', '🇯🇵 日本节点', '🇬🇧 英国节点', '🇰🇷 韩国节点', '🚀 手动切换1',
        '🚀 手动切换2', '🚀 手动切换3',
      ],
    },
    {
      name: '📢 谷歌FCM',
      type: 'select',
      proxies: [
        'DIRECT', '🚀 节点选择', '🇺🇲 美国节点', '🇭🇰 香港节点', '🇨🇳 台湾节点',
        '🇸🇬 狮城节点', '🇯🇵 日本节点', '🇬🇧 英国节点', '🇰🇷 韩国节点', '🚀 手动切换1',
        '🚀 手动切换2', '🚀 手动切换3',
      ],
    },
    {
      name: 'Ⓜ️ 微软云盘',
      type: 'select',
      proxies: [
        'DIRECT', '🚀 节点选择', '🇺🇲 美国节点', '🇭🇰 香港节点', '🇨🇳 台湾节点',
        '🇸🇬 狮城节点', '🇯🇵 日本节点', '🇬🇧 英国节点', '🇰🇷 韩国节点', '🚀 手动切换1',
        '🚀 手动切换2', '🚀 手动切换3',
      ],
    },
    {
      name: 'Ⓜ️ 微软服务',
      type: 'select',
      proxies: [
        'DIRECT', '🚀 节点选择', '🇺🇲 美国节点', '🇭🇰 香港节点', '🇨🇳 台湾节点',
        '🇸🇬 狮城节点', '🇯🇵 日本节点', '🇬🇧 英国节点', '🇰🇷 韩国节点', '🚀 手动切换1',
        '🚀 手动切换2', '🚀 手动切换3',
      ],
    },
    {
      name: '🍎 苹果服务',
      type: 'select',
      proxies: [
        'DIRECT', '🚀 节点选择', '🇺🇲 美国节点', '🇭🇰 香港节点', '🇨🇳 台湾节点',
        '🇸🇬 狮城节点', '🇯🇵 日本节点', '🇬🇧 英国节点', '🇰🇷 韩国节点', '🚀 手动切换1',
        '🚀 手动切换2', '🚀 手动切换3',
      ],
    },
    {
      name: '🎮 XBOX',
      type: 'select',
      proxies: [
        'DIRECT', '🚀 节点选择', '🇺🇲 美国节点', '🇭🇰 香港节点', '🇨🇳 台湾节点',
        '🇸🇬 狮城节点', '🇯🇵 日本节点', '🇬🇧 英国节点', '🇰🇷 韩国节点', '🚀 手动切换1',
        '🚀 手动切换2', '🚀 手动切换3',
      ],
    },
    {
      name: '🎮 游戏平台',
      type: 'select',
      proxies: [
        'DIRECT', '🚀 节点选择', '🇺🇲 美国节点', '🇭🇰 香港节点', '🇨🇳 台湾节点',
        '🇸🇬 狮城节点', '🇯🇵 日本节点', '🇬🇧 英国节点', '🇰🇷 韩国节点', '🚀 手动切换1',
        '🚀 手动切换2', '🚀 手动切换3',
      ],
    },
    {
      name: '🎮 游戏下载',
      type: 'select',
      proxies: [
        'DIRECT', '🚀 节点选择', '🇺🇲 美国节点', '🇭🇰 香港节点', '🇨🇳 台湾节点',
        '🇸🇬 狮城节点', '🇯🇵 日本节点', '🇬🇧 英国节点', '🇰🇷 韩国节点', '🚀 手动切换1',
        '🚀 手动切换2', '🚀 手动切换3',
      ],
    },
    {
      name: '🎮 Unity3D',
      type: 'select',
      proxies: [
        'DIRECT', '🚀 节点选择', '🇺🇲 美国节点', '🇭🇰 香港节点', '🇨🇳 台湾节点',
        '🇸🇬 狮城节点', '🇯🇵 日本节点', '🇬🇧 英国节点', '🇰🇷 韩国节点', '🚀 手动切换1',
        '🚀 手动切换2', '🚀 手动切换3',
      ],
    },
    {
      name: '🎯 全球直连',
      type: 'select',
      proxies: ['DIRECT', '🚀 节点选择', '♻️ 自动选择'],
    },
    { name: '🛑 广告拦截', type: 'select', proxies: ['REJECT', 'DIRECT'] },
    { name: '🍃 应用净化', type: 'select', proxies: ['REJECT', 'DIRECT'] },
    { name: '🆎 AdBlock', type: 'select', proxies: ['REJECT', 'DIRECT'] },
    { name: '🛡️ 隐私防护', type: 'select', proxies: ['REJECT', 'DIRECT'] },
    {
      name: '🐟 漏网之鱼',
      type: 'select',
      proxies: [
        '🚀 节点选择', '♻️ 自动选择', 'DIRECT', '🇭🇰 香港节点', '🇨🇳 台湾节点',
        '🇸🇬 狮城节点', '🇯🇵 日本节点', '🇺🇲 美国节点', '🇬🇧 英国节点', '🇰🇷 韩国节点',
        '🚀 手动切换1', '🚀 手动切换2', '🚀 手动切换3',
      ],
    },
    {
      name: '🇭🇰 香港节点',
      type: 'url-test',
      proxies: ['Proxy1', 'Proxy2'],
      filter: '(港|HK|Hong Kong)',
      url: 'http://www.gstatic.com/generate_204',
      interval: 300,
      tolerance: 50,
    },
    {
      name: '🇯🇵 日本节点',
      type: 'url-test',
      proxies: ['Proxy1', 'Proxy2'],
      filter: '(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)',
      url: 'http://www.gstatic.com/generate_204',
      interval: 300,
      tolerance: 50,
    },
    {
      name: '🇺🇲 美国节点',
      type: 'url-test',
      proxies: ['Proxy1', 'Proxy2'],
      filter: '(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)',
      url: 'http://www.gstatic.com/generate_204',
      interval: 300,
      tolerance: 150,
    },
    {
      name: '🇬🇧 英国节点',
      type: 'url-test',
      proxies: ['Proxy1', 'Proxy2'],
      filter: '(英国|英|UK|United Kingdom|Great Britain)',
      url: 'http://www.gstatic.com/generate_204',
      interval: 300,
      tolerance: 50,
    },
    {
      name: '🇨🇳 台湾节点',
      type: 'url-test',
      proxies: ['Proxy1', 'Proxy2'],
      filter: '(台|新北|彰化|TW|Taiwan)',
      url: 'http://www.gstatic.com/generate_204',
      interval: 300,
      tolerance: 50,
    },
    {
      name: '🇸🇬 狮城节点',
      type: 'url-test',
      proxies: ['Proxy1', 'Proxy2'],
      filter: '(新加坡|坡|狮城|SG|Singapore)',
      url: 'http://www.gstatic.com/generate_204',
      interval: 300,
      tolerance: 50,
    },
    {
      name: '🇰🇷 韩国节点',
      type: 'url-test',
      proxies: ['Proxy1', 'Proxy2'],
      filter: '(KR|Korea|KOR|首尔|韩|韓)',
      url: 'http://www.gstatic.com/generate_204',
      interval: 300,
      tolerance: 50,
    },
  ],
  'rule-providers': {
    local_area_network: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list',
      interval: 86400,
      format: 'text',
    },
    unban: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list',
      interval: 86400,
      format: 'text',
    },
    ban_ad: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list',
      interval: 86400,
      format: 'text',
    },
    ban_program_ad: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list',
      interval: 86400,
      format: 'text',
    },
    ban_easylist: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list',
      interval: 86400,
      format: 'text',
    },
    ban_easylist_china: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list',
      interval: 86400,
      format: 'text',
    },
    ban_easyprivacy: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list',
      interval: 86400,
      format: 'text',
    },
    google: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.list',
      interval: 86400,
      format: 'text',
    },
    google_fcm: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list',
      interval: 86400,
      format: 'text',
    },
    onedrive: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list',
      interval: 86400,
      format: 'text',
    },
    microsoft: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list',
      interval: 86400,
      format: 'text',
    },
    microsoft_custom: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/Oegi3K/clash_rule_custom/main/microsoft_custom.list',
      interval: 86400,
      format: 'text',
    },
    apple: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list',
      interval: 86400,
      format: 'text',
    },
    category_communication: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-communication.list',
      interval: 86400,
      format: 'text',
    },
    openai: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/openai.list',
      interval: 86400,
      format: 'text',
    },
    category_ai_not_cn: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.list',
      interval: 86400,
      format: 'text',
    },
    xbox: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Xbox.list',
      interval: 86400,
      format: 'text',
    },
    epic: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list',
      interval: 86400,
      format: 'text',
    },
    origin: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list',
      interval: 86400,
      format: 'text',
    },
    blizzard: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Blizzard.list',
      interval: 86400,
      format: 'text',
    },
    sony: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list',
      interval: 86400,
      format: 'text',
    },
    steam: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list',
      interval: 86400,
      format: 'text',
    },
    nintendo: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list',
      interval: 86400,
      format: 'text',
    },
    game_download: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GameDownload.list',
      interval: 86400,
      format: 'text',
    },
    youtube: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list',
      interval: 86400,
      format: 'text',
    },
    netflix: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list',
      interval: 86400,
      format: 'text',
    },
    bahamut: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list',
      interval: 86400,
      format: 'text',
    },
    bilibili_hmt: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list',
      interval: 86400,
      format: 'text',
    },
    bilibili: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list',
      interval: 86400,
      format: 'text',
    },
    china_media: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list',
      interval: 86400,
      format: 'text',
    },
    proxy_media: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list',
      interval: 86400,
      format: 'text',
    },
    proxy_gfwlist: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list',
      interval: 86400,
      format: 'text',
    },
    adobe: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/adobe.list',
      interval: 86400,
      format: 'text',
    },
    crypto: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Crypto.list',
      interval: 86400,
      format: 'text',
    },
    paypal: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PayPal/PayPal.list',
      interval: 86400,
      format: 'text',
    },
    unity: {
      type: 'http',
      behavior: 'domain',
      url: 'https://raw.githubusercontent.com/Oegi3K/clash_rule_custom/main/unity.list',
      interval: 86400,
      format: 'text',
    },
  },
  rules: [
    'RULE-SET,local_area_network,🎯 全球直连',
    'RULE-SET,unban,🎯 全球直连',
    'RULE-SET,ban_ad,🛑 广告拦截',
    'RULE-SET,ban_program_ad,🍃 应用净化',
    'RULE-SET,ban_easylist,🆎 AdBlock',
    'RULE-SET,ban_easylist_china,🆎 AdBlock',
    'RULE-SET,ban_easyprivacy,🛡️ 隐私防护',
    'RULE-SET,google,🇬 谷歌服务',
    'RULE-SET,google_fcm,📢 谷歌FCM',
    'RULE-SET,onedrive,Ⓜ️ 微软云盘',
    'RULE-SET,microsoft,Ⓜ️ 微软服务',
    'RULE-SET,microsoft_custom,Ⓜ️ 微软服务',
    'RULE-SET,apple,🍎 苹果服务',
    'RULE-SET,category_communication,💬 即时通讯',
    'GEOIP,telegram,💬 即时通讯,no-resolve',
    'RULE-SET,openai,🤖 ChatGPT',
    'RULE-SET,category_ai_not_cn,🤖 AI服务',
    'RULE-SET,xbox,🎮 XBOX',
    'RULE-SET,epic,🎮 游戏平台',
    'RULE-SET,origin,🎮 游戏平台',
    'RULE-SET,blizzard,🎮 游戏平台',
    'RULE-SET,sony,🎮 游戏平台',
    'RULE-SET,steam,🎮 游戏平台',
    'RULE-SET,nintendo,🎮 游戏平台',
    'RULE-SET,game_download,🎮 游戏下载',
    'RULE-SET,youtube,📹 油管视频',
    'RULE-SET,netflix,🎥 奈飞视频',
    'RULE-SET,bahamut,📺 巴哈姆特',
    'RULE-SET,bilibili_hmt,📺 哔哩哔哩',
    'RULE-SET,bilibili,📺 哔哩哔哩',
    'RULE-SET,china_media,🌏 国内媒体',
    'RULE-SET,proxy_media,🌍 国外媒体',
    'RULE-SET,proxy_gfwlist,🚀 节点选择',
    'RULE-SET,adobe,🚀 节点选择',
    'RULE-SET,crypto,💰 Crypto',
    'RULE-SET,paypal,💰 PayPal',
    'RULE-SET,unity,🎮 Unity3D',
    'GEOIP,LAN,🎯 全球直连',
    'GEOIP,CN,🎯 全球直连',
    'MATCH,🐟 漏网之鱼',
  ],
};

// Convert to YAML
const yamlOutput = yaml.dump(config, { lineWidth: -1 });

// Output to console (or save to file)
console.log(yamlOutput);

// Optional: Save to file
const fs = require('fs');
fs.writeFileSync('clash_meta_config.yaml', yamlOutput, 'utf8');
console.log('Configuration saved to clash_meta_config.yaml');